Check courier conf file during install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,5 +5,13 @@ if [[ $(id -u) -ne 0 ]] ; then
     exit 1
 fi
 
+conffile=/etc/courier/imapd-ssl
+
+if [ ! -f $conffile ]
+then
+    echo "$confile not found, install courier-imap"
+    exit 1
+fi
+
 cp usr/local/bin/* /usr/local/bin/
 cp etc/cron.d/* /etc/cron.d/
